### ISSUE TITLE
Add fontconfig package for Tomcat on AdoptOpenJDK

### ISSUE THREAD

**Issue by padyx** [docker-library/tomcat#170]
With AdoptOpenJDK, there seems to be an issue regarding font configurations:
There is a NPE in the FontConfiguration class when the fonts are accessed. This is happening for us in the tomcat base image too.

**Related issues**
- AdoptOpenJDK: https://github.com/AdoptOpenJDK/openjdk-build/issues/693
- Adopt Docker image: https://github.com/AdoptOpenJDK/openjdk-docker/issues/75
- Adopt Docker image, number two: https://github.com/AdoptOpenJDK/openjdk-docker/issues/174

The fontconfig package was added already in the official docker image for OpenJDK (Official Docker image as a workaround: https://github.com/docker-library/openjdk/issues/46).

I suggest that the fontconfig library package is added to Tomcat image (AdoptOpenJDK version) as well, at least until OpenJDK / AdoptOpenJDK fixes the underlying issue.

**Reproduction**
1. Create a docker container of tomcat:9-jdk11-adoptopenjdk-hotspot
2. Add a simple webapp executing the snippet from https://github.com/AdoptOpenJDK/openjdk-docker/issues/75#issuecomment-503075868  - or use the attached maven project
[com.example.webapp.app2.zip](https://github.com/docker-library/tomcat/files/3534371/com.example.webapp.app2.zip) - or the following WAR file that I prebuilt for you:
[app.zip](https://github.com/docker-library/tomcat/files/3534376/app.zip)
3. Use docker cp to copy the resulting war file into the webapps folder
4. Check catalina.*.log for output

**Issue**
```
        java.util.concurrent.ExecutionException: java.lang.InternalError: java.lang.reflect.InvocationTargetException
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:779)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
                at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1620)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1151)
                at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
                at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
                at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by: java.lang.InternalError: java.lang.reflect.InvocationTargetException
                at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
                at java.desktop/sun.java2d.SunGraphicsEnvironment.getFontManagerForSGE(SunGraphicsEnvironment.java:189)
                at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:223)
                at java.desktop/sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(SunGraphicsEnvironment.java:251)
                at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getAvailableFontFamilyNames(HeadlessGraphicsEnvironment.java:75)
                at com.example.webapp.Main.contextInitialized(Main.java:12)
                at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4682)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5143)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
                ... 15 more
        Caused by: java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
                ... 35 more
        Caused by: java.lang.NullPointerException
                at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
                at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
                at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
                at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
                at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
                at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
                at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
                ... 40 more
```

**Proposed fix**
We've tested the following fix successfully:
```
FROM tomcat:9-jdk11-adoptopenjdk-hotspot
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      fontconfig \
 && rm -rf /var/lib/apt/lists/*
```

**Comment by tianon** [comment]
The AdoptOpenJDK image maintainers have opted to follow the `slim` variants of the `openjdk` image, and as such do not include this package (and that behavior is thus mirrored in the `slim` variants of `tomcat`).

**Comment by padyx** [comment]
Thanks for your response @tianon !

I can see that one could want to leave it out of the `slim` image version, but what about the regular non-slim image version of `tomcat`?

(I can push fixed images to the hub for myself, but so many people are running into this with anything Adopt based, as evidenced by the slew of bugs...)

**Comment by tianon** [comment]
Now there's another: https://github.com/AdoptOpenJDK/openjdk-docker/issues/211

I really think this should be fixed in the AdoptOpenJDK images themselves.

**Comment by wglambert** [comment]
Closing with the merge of this upstream PR https://github.com/AdoptOpenJDK/openjdk-docker/pull/224
