### ISSUE TITLE
SSLHandshakeException: Invalid ECDH ServerKeyExchange signature

### ISSUE THREAD

**Issue by gary094** [docker-library/tomcat#182]
Hello,

I'm facing a strange issue with one of my docker containers.

I'm developing using the following image on my local machine (x86_64):
tomcat:9.0.27-jdk11-openjdk-slim

which works totally fine.

Then, to deploy it on my raspberry pi I have another Dockerfile (arm32v7) which is using this image:
arm32v7/tomcat:9.0.27-jdk11-adoptopenjdk-hotspot

Now in my application I create some http client to call some http endpoint but on the raspberry I get the following exception:

`javax.net.ssl.SSLHandshakeException: Invalid ECDH ServerKeyExchange signature
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:254)
	at java.base/sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:325)
	at java.base/sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeConsumer.consume(ECDHServerKeyExchange.java:531)
	at java.base/sun.security.ssl.ServerKeyExchange$ServerKeyExchangeConsumer.consume(ServerKeyExchange.java:111)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.gsoft.util.SendNotification.sendNotification(SendNotification.java:49)
	at com.gsoft.notificationpage.NotificationPage$2.onSubmit(NotificationPage.java:64)
	at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:223)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1308)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:1001)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:825)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:176)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:127)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:598)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914)
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:299)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

The same functionality works totally fine on my x86 builds.

I hope you can give me some advice on this.

BR

**Comment by wglambert** [comment]
Looks like this was a bug that was fixed in 13 on [OpenJDK ](https://bugs.openjdk.java.net/browse/JDK-8216039?focusedCommentId=14275885&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14275885)

.27 is slightly old, you could try `9.0.30-jdk11-adoptopenjdk-hotspot` and see if it's resolved

Otherwise if your Pi is compatible with 64bit then one of the other variants might work 
https://hub.docker.com/r/arm64v8/tomcat/

**Comment by gary094** [comment]
Thanks, I tried .30 and unfortunately it does not work there either.

The CPU on my raspberry pi 3 is 64 Bit however I've got a 32 Bit OS running on it.
arm64v8 images won't work then unfortunately.

Is there any chance that this bug is going to get back ported into either .27 or .30 on the arm32v7 images?
Not sure about the state of the back port on the JDK bug ticket. It looks like it was disapproved.

**Comment by tianon** [comment]
Unfortunately, we don't have any visibility into that or control over it.

The best I can recommend is that you try the same variant on your amd64 machine as you're using on your ARM device so you're testing like-for-like and not using different distributions of Java (which could have potentially different patches applied).

**Comment by wglambert** [comment]
I'm going to close since there's nothing actionable for us to do here

**Comment by Humberd** [comment]
I encountered the similar issue. Hope this thread helps: https://stackoverflow.com/questions/61580867/deployed-app-cannot-exchange-oauth2-code-for-token
