### ISSUE TITLE
Tomcat couldn't find class in catalina.jar under tomcat lib folder

### ISSUE THREAD

**Issue by ilikerei** [docker-library/tomcat#218]
When I start the docker with my app, it seems tomcat couldn't find class in catalina.jar under it's own lib folder. I thought /usr/local/tomcat/lib folder is always involved. Not sure how it happened and how it could be fixed.

```
bash-4.4$ unzip -l /usr/local/tomcat/lib/catalina.jar | grep 'org.apache.catalina.valves.AbstractAccessLogValve.class'
    13581  03-14-2019 11:24   org/apache/catalina/valves/AbstractAccessLogValve.class
```

```bash-4.4$ catalina.sh run
Using CATALINA_BASE:   /app/config/catalina-base
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /app/appBase/temp
Using JRE_HOME:        /usr/lib/jvm/default-jvm/jre
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
......
java.lang.NoClassDefFoundError: org/apache/catalina/valves/AbstractAccessLogValve
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
2021-01-21T12:52:58,892[E][o.a.t.u.d.Digester][main]: - Begin event threw error java.lang.ClassNotFoundException: org.apache.catalina.valves.AbstractAccessLogValve
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]	... 36 moreWrapped by: java.lang.NoClassDefFoundError: org/apache/catalina/valves/AbstractAccessLogValve
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_201]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_201]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_201]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_201]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_201]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_201]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:116) ~[?:?]
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1250) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_201]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[?:1.8.0_201]
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1518) ~[?:?]
	at org.apache.catalina.startup.Catalina.load(Catalina.java:611) ~[?:?]
	at org.apache.catalina.startup.Catalina.load(Catalina.java:662) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309) ~[bootstrap.jar:8.5.39]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492) ~[bootstrap.jar:8.5.39]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:116)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1250)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1518)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:611)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:662)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.valves.AbstractAccessLogValve
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
```

**Comment by tianon** [comment]
I think we're going to need a bit more information to reproduce?  Perhaps a really minimal `Dockerfile` that demonstrates the problem?

**Comment by ilikerei** [comment]
This similar issue shed a light for me:
[https://stackoverflow.com/a/54310301/7751343](url)
  Some libs may completely override the base tomcat_home/lib. I reviewed our path and libs finally found that if one of our customized jar is in java.ext.dirs (-Djava.ext.dirs=/xxx/lib) then tomcat just couldn't load jars under base tomcat_home/lib. 
The customized valve class failed because the 'org.apache.catalina.valves.AbstractAccessLogValve.class' inside catalina.jar couldn't be found.
  DOn't know the reason but found solution anyway.

**Comment by yosifkit** [comment]
Seems resolved
