### ISSUE TITLE
Exception message "java.lang.IllegalArgumentException" is output in Tomcat when log in to ThingWorx

### ISSUE THREAD

**Issue by meghatalathi** [docker-library/tomcat#317]
**Issue Report: Apache Tomcat Unicode Exception**
**Description**
The customer has been running ThingWorx 9.2.11 HA configuration since October 1st. They have observed the following exception appearing frequently in the logs, particularly during user login to ThingWorx:

23-Oct-2023 17:18:31.161 WARNING [https-jsse-nio-443-exec-1] org.apache.coyote.http11.Http11Processor.prepareResponse The HTTP response header [Last-Modified] with value [木, 11 5月 2023 21:15:43 JST] has been removed from the response because it is invalid
	java.lang.IllegalArgumentException: The Unicode character [木] at code point [26,408] cannot be encoded as it is outside the permitted range of 0 to 255
		at org.apache.tomcat.util.buf.MessageBytes.toBytesSimple(MessageBytes.java:286)
		at org.apache.tomcat.util.buf.MessageBytes.toBytes(MessageBytes.java:255)
		at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:394)
		at org.apache.coyote.http11.Http11OutputBuffer.sendHeader(Http11OutputBuffer.java:372)
		at org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1065)
		at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:379)
		at org.apache.coyote.Response.action(Response.java:211)
		at org.apache.coyote.Response.sendHeaders(Response.java:440)
		at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:292)
		at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:273)
		at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
		at com.thingworx.webservices.context.HttpExecutionContext.commitResponse(HttpExecutionContext.java:535)
		at com.thingworx.webservices.BaseService.handleCommittingResponse(BaseService.java:625)
		at com.thingworx.webservices.BaseService.service(BaseService.java:612)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at com.thingworx.security.contenttype.ContentTypeFilter.doFilter(ContentTypeFilter.java:138)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at com.thingworx.security.contenttype.ContentLengthFilter.doFilter(ContentLengthFilter.java:73)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at com.thingworx.security.filter.ValidationFilter.doFilter(ValidationFilter.java:22)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at com.thingworx.security.authentication.AuthenticationFilter.propagateRequest(AuthenticationFilter.java:735)
		at com.thingworx.security.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at com.thingworx.security.filter.ClickjackFilter.doFilter(ClickjackFilter.java:208)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at com.thingworx.security.filter.HttpResponseHeadersFilter.doFilter(HttpResponseHeadersFilter.java:172)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)

The exception does not affect ThingWorx behavior, but the customer wants to understand the cause and how to prevent it. They also need confirmation that the message does not affect ThingWorx.

**Configuration and Reproduction**
We have tested this on different ThingWorx and Tomcat configurations with the following results:

**ThingWorx 9.3.5, Tomcat/Apache 9.0.35, Amazon-corretto-11.0.13.8.1: Not Reproduced
ThingWorx 9.3.7, Tomcat/Apache 9.0.35, Amazon-corretto-11.0.13.8.1: Not Reproduced
ThingWorx 9.4.5, Tomcat/Apache 9.0.84, Java JDK 11.0.17: Reproduced
ThingWorx 9.5.0 (Foundation), Tomcat/Apache 9.0.82, Java JDK 11.0.12: Reproduced
ThingWorx 9.3.2 (Foundation), Tomcat/Apache 9.0.56, Java JDK 11.0.12: Not Reproduced**

**Analysis**
The issue appears to be related to a change in Tomcat versions. It is not present in Tomcat 9.0.35 but consistently reproduces with Tomcat 9.0.82 onwards. The HTTP response header Last-Modified contains a Unicode character (木) that cannot be encoded within the permitted range for HTTP headers (0 to 255), causing Tomcat to throw an IllegalArgumentException.

Relevant bug reports from [apache.org](http://apache.org/):

[66512 – File downloads render as empty if access to Tomcat based application is delegated via AJP](https://bz.apache.org/bugzilla/show_bug.cgi?id=66512) 

[66196 – HTTP/1 connector doesn't blow-up when HTTP header contains non-ASCII characters](https://bz.apache.org/bugzilla/show_bug.cgi?id=66196)

**Request for Assistance**
Could you please provide guidance on how to solve this issue? We need to:

1.Understand the root cause of this exception.
2. Find a solution to prevent this exception.
3. Confirm that the exception does not impact ThingWorx functionality.
Logs are attached for more details.

[catalina.2023-10-23.log](https://github.com/user-attachments/files/16056146/catalina.2023-10-23.log)

**Comment by tianon** [comment]
This is likely an issue with ThingWorx or the configuration, not Tomcat upstream _or_ our packaging of Tomcat (which is fairly vanilla -- even our default configuration is Tomcat's own default configuration).  I would suggest finding a suitable support forum or ThingWorx contractor who can help you debug/diagnose further.
